name: Build binaries

on:
  push:
    branches:
      - autobuild

env:
  BUILD_TYPE: Release

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: AlexandreRouma/SDRPlusPlus

    - uses: actions/checkout@v2
      with:
        path: decoder_modules/sdrpp_radiosonde
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install libfftw3-dev libglfw3-dev libglew-dev libvolk2-dev libsoapysdr-dev libairspyhf-dev libairspy-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev librtlsdr-dev libbladerf-dev liblimesuite-dev p7zip-full wget portaudio19-dev libcodec2-dev libssl-dev

    - name: Patch CMakeLists.txt
      run: cp ${{github.workspace}}/decoder_modules/sdrpp_radiosonde/.github/workflows/CMakeLists.txt ${{github.workspace}}

    - name: Configure
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target radiosonde_decoder

    - uses: actions/upload-artifact@v2
      with:
        name: radiosonde_decoder.so
        path: ${{github.workspace}}/build/decoder_modules/sdrpp_radiosonde/radiosonde_decoder.so


  build_windows:
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v2
      with:
        repository: AlexandreRouma/SDRPlusPlus

    - uses: actions/checkout@v2
      with:
        path: decoder_modules/sdrpp_radiosonde
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Download PothosSDR
      run: Invoke-WebRequest -Uri "https://downloads.myriadrf.org/builds/PothosSDR/PothosSDR-2020.01.26-vc14-x64.exe" -OutFile ${{runner.workspace}}/pothos.exe

    - name: Install PothosSDR
      run: mkdir "C:/Program Files/PothosSDR" ; 7z x ${{runner.workspace}}/pothos.exe -o"C:/Program Files/PothosSDR/"

    - name: Download libusb
      run: Invoke-WebRequest -Uri "https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z" -OutFile ${{runner.workspace}}/libusb.7z

    - name: Patch Pothos with earlier libusb version
      working-directory: ${{runner.workspace}}
      run: 7z x libusb.7z -olibusb_old ; rm "C:/Program Files/PothosSDR/bin/libusb-1.0.dll" ; cp "libusb_old/MS64/dll/libusb-1.0.dll" "C:/Program Files/PothosSDR/bin/"

    - name: Download SDRPlay API
      run: Invoke-WebRequest -Uri "https://drive.google.com/uc?id=12UHPMwkfa67A11QZDmpCT4iwHnyJHWuu" -OutFile ${{runner.workspace}}/SDRPlay.zip

    - name: Install SDRPlay API
      run: 7z x ${{runner.workspace}}/SDRPlay.zip -o"C:/Program Files/"

    - name: Download codec2
      run: git clone https://github.com/AlexandreRouma/codec2

    - name: Prepare MinGW
      run: C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "pacman --noconfirm -S --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja"

    - name: Prepare build for codec2
      run: cd codec2 ; mkdir build ; cd build ; C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "cmake .. -DCMAKE_GNUtoMS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-static-libgcc"

    - name: Build codec2
      run: cd codec2/build ; C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "ninja"

    - name: Install codec2
      run: mkdir "C:/Program Files/codec2" ; mkdir "C:/Program Files/codec2/include" ; mkdir "C:/Program Files/codec2/include/codec2" ; mkdir "C:/Program Files/codec2/lib" ; cd "codec2" ; xcopy "src" "C:/Program Files/codec2/include" ; cd "build" ; xcopy "src" "C:/Program Files/codec2/lib" ; xcopy "codec2" "C:/Program Files/codec2/include/codec2"

    - name: Install vcpkg dependencies
      run: vcpkg install fftw3:x64-windows glew:x64-windows glfw3:x64-windows portaudio:x64-windows openssl-windows:x64-windows

    - name: Install rtaudio
      run: git clone https://github.com/thestk/rtaudio ; cd rtaudio ; git checkout 2f2fca4502d506abc50f6d4473b2836d24cfb1e3 ; mkdir build ; cd build ; cmake .. ; cmake --build . --config Release ; cmake --install .

    - name: Patch CMakeLists.txt
      run: cp ${{github.workspace}}/decoder_modules/sdrpp_radiosonde/.github/workflows/CMakeLists.txt ${{github.workspace}}

    - name: Configure
      run: cmake "$Env:GITHUB_WORKSPACE" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build "$Env:GITHUB_WORKSPACE" --config ${{env.BUILD_TYPE}} --target radiosonde_decoder 

    - uses: actions/upload-artifact@v2
      with:
        name: radiosonde_decoder.dll
        path: ${{github.workspace}}\decoder_modules\sdrpp_radiosonde\Release\radiosonde_decoder.dll
